### ISSUE TITLE
Downloads fail when behind proxy

### ISSUE THREAD

**Issue by wtbarnes** [Cadair/parfive#23]
Any downloads behind a proxy hang indefinitely.

I realize this is difficult to test so I'm happy to be the guinea pig for any proposed fixes! Of course, all proxies may be slightly different as well...

## MWE

```python
>>> from parfive import Downloader
>>> dl = Downloader()
>>> dl.enqueue_file("http://data.sunpy.org/sample-data/predicted-sunspot-radio-flux.txt", path="./")
>>> files = dl.download()  # <-- this hangs forever
```

Also true when downloading sample data in sunpy or doing any query with `sunpy.net.Fido`.

**Comment by wtbarnes** [comment]
It appears I should've just looked at the aiohttp docs first. As noted [here](http://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support), it looks like you can just pass a url to the session with `proxy='my-proxy-url'`. Presumably this would happen [here](
https://github.com/Cadair/parfive/blob/master/parfive/downloader.py#L285)? 

The main issue of course is how best to propagate this configuration option...

**Comment by wtbarnes** [comment]
Ok this is solved by just passing `proxy='my-proxy-url'` to `enqueue_file` so not actually an issue. However, this is likely a problem downstream in sunpy as I'm not sure we allow kwargs to be passed to `enqueue_file`.

**Comment by Cadair** [comment]
I think we should support proxy env vars, and maybe also tie it into #32 and generally allow passing session vars to the constructor of `Downloader()`.

**Comment by Raahul-Singh** [comment]
@Cadair should I start working on this?

**Comment by wtbarnes** [comment]
Now that #32 has been merged, can this be closed?
