### ISSUE TITLE
Support HTTP Basic Auth

### ISSUE THREAD

**Issue by Cadair** [Cadair/parfive#29]
This involves a way of passing arguments to `aiohttp.ClientSession` which means doing it at construct time (or via properties) as we only use one session per call to `download()`.

**Comment by Raahul-Singh** [comment]
Since the constructor of  `aiohttp.ClientSession` allows an `auth` parameter, may we simply add the basic auth as an instance variable to `Downloader`?

**Comment by Cadair** [comment]
I don't want to replicate the whole `aiohttp.ClientSession` signature in `Download()` so maybe we should just allow a `http_session` dictionary which gets passed through or something?

Eitherway, we really need to document how to pass what kwargs to what through parfive.

**Comment by vn-ki** [comment]
Why don't we pass the session to the downloader? This would give more freedom down the line. Whatever the kind of auth is, the user can do the auth and pass the corresponding session down to the downloader?

**Comment by malteos** [comment]
Thanks for this project. Could you please provide one example of how to use HTTP Auth with `SessionConfig`.
