### ISSUE TITLE
python 3.8 deprecation warning

### ISSUE THREAD

**Issue by dstansby** [Cadair/parfive#41]
I'm seeing this with python 3.8 and parfive:
```python
/home/vsts/work/1/s/.tox/py38-online/lib/python3.8/site-packages/parfive/downloader.py:101: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self.http_tokens = asyncio.Queue(maxsize=self.max_conn, loop=self.loop)
```

**Comment by Cadair** [comment]
Thanks :smile:

I don't just want to change the code before understanding the ramifications. parfive by default spins up a new loop in a threadpool which can be different from other running loops, so it's important that we are using the right one.
