### ISSUE TITLE
Does parfive still support python 3.6?

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Cadair/parfive#45]
Readme requirements states, it requires python 3.7+ while pypi and github description says it supports 3.6+

**Comment by Cadair** [comment]
Ah sorry, no 1.1 dropped support for Python 3.6. I should update the readme. Thanks :smile:

**Comment by Cadair** [comment]
I think I got everywhere.

**Comment by GitHK** [comment]
I will link back to this question even if closed. What was the reason for dropping support of python 3.6?

**Comment by Cadair** [comment]
There were enough changes to the asyncio stuff that it made sense to me to follow along with sunpy's (the package that spawned this project) adherence to https://numpy.org/neps/nep-0029-deprecation_policy.html

Where it makes sense I probably will run a little slower than NEP 29 for this package, but I maintain this in my spare time (it's a side project on a side project) so I am always likely to bump Python versions if it makes things easier for me. (I promise I wont go any faster than NEP 29).
