### ISSUE TITLE
Python 3.6 with parfive 1.0.x and aioftp

### ISSUE THREAD

**Issue by nabobalis** [Cadair/parfive#51]
`E AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'` on the sunpy 2.0.X conda (py36) build.

Looks like the conda build uses parfive 1.0.2 and this has errored. 

```
../../.tox/py36-conda/lib/python3.6/site-packages/sunpy/data/__init__.py:5: in <module>
    from sunpy.data._sample import download_sample_data
../../.tox/py36-conda/lib/python3.6/site-packages/sunpy/data/_sample.py:7: in <module>
    from sunpy.util.parfive_helpers import Downloader
../../.tox/py36-conda/lib/python3.6/site-packages/sunpy/util/parfive_helpers.py:5: in <module>
    import parfive
../../.tox/py36-conda/lib/python3.6/site-packages/parfive/__init__.py:5: in <module>
    from .downloader import Downloader
../../.tox/py36-conda/lib/python3.6/site-packages/parfive/downloader.py:17: in <module>
    import aioftp
../../.tox/py36-conda/lib/python3.6/site-packages/aioftp/__init__.py:4: in <module>
    from .client import *
../../.tox/py36-conda/lib/python3.6/site-packages/aioftp/client.py:553: in <module>
    class Client(BaseClient):
../../.tox/py36-conda/lib/python3.6/site-packages/aioftp/client.py:1164: in Client
    @contextlib.asynccontextmanager
E   AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'
```

**Comment by Cadair** [comment]
I think this just that aioftp have released an update which breaks us.

**Comment by nabobalis** [comment]
Pin the version for the 1.0 branch?

**Comment by Cadair** [comment]
This is an issue with the aioftp conda feedstock, it needs fixing in our feedstock. https://github.com/conda-forge/aioftp-feedstock/issues/10

**Comment by nabobalis** [comment]
It was merged, so I will restart a 2.0 build and see if its ok.

**Comment by nabobalis** [comment]
https://dev.azure.com/sunpy/sunpy/_build/results?buildId=9478&view=logs&j=914b910f-9fe0-56db-ed32-711cc55e4769&t=b8273cec-fe0d-57ea-20a5-8bf5bf8061a5

**Comment by nabobalis** [comment]
REstarted the build here: https://dev.azure.com/sunpy/sunpy/_build/results?buildId=9505&view=logs&j=914b910f-9fe0-56db-ed32-711cc55e4769&t=914b910f-9fe0-56db-ed32-711cc55e4769 
it passes
