### ISSUE TITLE
Propagate the URL which is associated with each file path through to the Results object

### ISSUE THREAD

**Issue by Cadair** [Cadair/parfive#71]
It would be useful if the `Results` object had a property which mapped input URL to output filename, as the filename is normally provided by the `Content-Disposition` headers on the download request, so is not known to the user at the point they call download.

**Comment by dreamflasher** [comment]
I agree that this would be really helpful, and it would allow me to write a workaround for https://github.com/Cadair/parfive/issues/122 -- but... I am already getting something back in the results? The completed result lists shows me a list of files, and they do exist on disk. What's missing is the origin URL, that would be helpful, too... but I wonder if this ticket might already be solved?

**Comment by Cadair** [comment]
I am not entirely sure how this would help you work around #122, this issue is to be able to know which URL generated which completed file.
