### ISSUE TITLE
User specified headers are ignored if User-Agent isn't specified

### ISSUE THREAD

**Issue by karl0ss** [Cadair/parfive#85]
Maybe I'm missing something but I am trying to pass in headers as such - 

```
dl = Downloader(
    headers=dict(one=1, two=2, three=3)
)
```

But they do not seem to be getting set and in dl.headers all i see is 
`{'User-Agent': 'parfive/1.5.1 aiohttp/3.8.1 python/3.8.1'}`

Hope someone can shed some light on what I am doing wrong...

Thanks

**Comment by karl0ss** [comment]
I would seem that you have to include a User-Agent as one of your passed in headers or it doesn't work.

**Comment by Cadair** [comment]
Yeah, I would say that's a bug, this line here:

https://github.com/Cadair/parfive/blob/13cbd9d3164c7504258dedc2eb7430f37591f73e/parfive/downloader.py#L97-L99

should update the headers dict if it exists but user agent isn't in it rather than overwrite it.
